name: Simple Workflow

on:
    workflow_dispatch:
        inputs:
            user_value:
                description: 'Insert your parameter'
                required: true
                default: 'Some_default_value'
env:
    USER_VALUE: ${{ github.event.inputs.user_value }}

jobs:

    GIT-HOMEWORK:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v2
        - name: 1.1 INPUT PARAMETER TO TXT FILE
          run: echo "${{ github.event.inputs.user_value }}" > parameter.txt
        - name: 1.2 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: parameter.txt
              path: /home/runner/work/devops-school/devops-school/parameter.txt
              
        - name: 2.1 UPLOADING FILES
          run: |
            cp ./scripts/main.py ./.github/actions/action_1.2/main.py
        - name: 2.2 EXECUTING THE PYTHON SCRIPT
          uses: ./.github/actions/action_1.2
        - name: 2.3 DOWNLOAD ARTIFACT
          uses: actions/upload-artifact@v2
          with:
              name: log.md
              path: /home/runner/work/devops-school/devops-school/log.md
